# -*- coding: utf-8 -*-
# Generated by Django 1.9.5 on 2016-04-08 03:09
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('cyoa', '0001_initial'),
    ]

    operations = [
        migrations.DeleteModel(
            name='ActivityType',
        ),
        migrations.DeleteModel(
            name='Adventure',
        ),
        migrations.DeleteModel(
            name='Location',
        ),
    ]
