# -*- coding: utf-8 -*-
# Generated by Django 1.9.5 on 2016-04-09 02:19
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('cyoa', '0003_auto_20160408_0309'),
    ]

    operations = [
        migrations.CreateModel(
            name='ActivityHours',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('weekday', models.IntegerField(choices=[(1, 'Monday'), (2, 'Tuesday'), (3, 'Wednesday'), (4, 'Thursday'), (5, 'Friday'), (6, 'Saturday'), (7, 'Sunday')])),
                ('open_time', models.TimeField()),
                ('open_duration', models.DurationField()),
            ],
        ),
        migrations.AddField(
            model_name='activity',
            name='facebook_url',
            field=models.CharField(max_length=400, null=True),
        ),
        migrations.AddField(
            model_name='activity',
            name='maps_url',
            field=models.CharField(max_length=400, null=True),
        ),
        migrations.AddField(
            model_name='activity',
            name='url',
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='activityhours',
            name='activity',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='cyoa.Activity'),
        ),
        migrations.AlterUniqueTogether(
            name='activityhours',
            unique_together=set([('activity', 'weekday')]),
        ),
    ]
