# -*- coding: utf-8 -*-
# Generated by Django 1.9.5 on 2016-04-09 02:29
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cyoa', '0004_auto_20160409_0219'),
    ]

    operations = [
        migrations.AlterField(
            model_name='activity',
            name='facebook_url',
            field=models.CharField(blank=True, max_length=400, null=True),
        ),
        migrations.AlterField(
            model_name='activity',
            name='maps_url',
            field=models.CharField(blank=True, max_length=400, null=True),
        ),
        migrations.AlterField(
            model_name='activity',
            name='url',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='adventure',
            name='date_finished',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
