# -*- coding: utf-8 -*-
# Generated by Django 1.9.5 on 2016-04-09 05:40
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('cyoa', '0005_auto_20160409_0229'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='activity',
            options={'verbose_name_plural': 'Activities'},
        ),
        migrations.AlterModelOptions(
            name='activityhours',
            options={'verbose_name_plural': 'Activity Hours'},
        ),
        migrations.AlterModelOptions(
            name='activitytype',
            options={'verbose_name_plural': 'Activity Types'},
        ),
        migrations.AlterModelOptions(
            name='adventure',
            options={'verbose_name_plural': 'Adventures'},
        ),
    ]
